# ====================================
# FORMEX - PRODUCCIÓN (RENDER / RAILWAY)
# ====================================

server.port=${PORT:8080}

# --- BASE DE DATOS (PostgreSQL / Neon) ---
# Render inyecta la variable DATABASE_URL automáticamente
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
# CAMBIO CRÍTICO: Usar Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public
# CAMBIO CRÍTICO: Usar Dialecto de PostgreSQL
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# --- SEGURIDAD (JWT) ---
formex.app.jwtSecret=${JWT_SECRET}
formex.app.jwtExpirationMs=86400000

# --- STRIPE (Pagos) ---
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.public.key=${STRIPE_PUBLIC_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

# --- AUTH0 VALIDACIÓN (Resource Server) ---
# Para que el Backend acepte los tokens del Frontend
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_ISSUER_URI}
auth0.audience=${AUTH0_AUDIENCE}

# --- AUTH0 GESTIÓN (Machine to Machine) ---
# Para que el Backend pueda crear usuarios automáticamente
auth0.domain=${AUTH0_DOMAIN}
auth0.management.client-id=${AUTH0_MGT_CLIENT_ID}
auth0.management.client-secret=${AUTH0_MGT_CLIENT_SECRET}

# --- CORS (Frontend) ---
app.cors.allowed-origins=${FRONTEND_URL}
app.frontend.url=${FRONTEND_URL}


# --- LOGGING ---
logging.level.root=WARN
logging.level.com.superinka.formex=INFO


# --- MULTIPART ---
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.file-size-threshold=2KB


cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}


# ===============================
# RESEND
# ===============================
resend.api.key=${RESEND_API_KEY}